SRC += muse.c
COMMAND_ENABLE = no
AUDIO_ENABLE = yes
BACKLIGHT_ENABLE = no
KEY_LOCK_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_MACRO_NO_NESTING = true
MOUSEKEY_ENABLE = yes
OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

USER_NAME := zacwm
