#pragma once

#define NO_DEBUG
#define NO_PRINT
#define NO_USB_STARTUP_CHECK

#define MK_VARIANT MK_TYPE_KINETIC

#define MK_KINETIC_MOUSE_MAXS 72
#define MK_KINETIC_MOUSE_ACCN 22
#define MK_KINETIC_MOUSE_FRIC 14
#define MK_KINETIC_MOUSE_DRAG 18

#define MK_KINETIC_WHEEL_MAXS 1
#define MK_KINETIC_WHEEL_ACCN 16

#ifdef AUDIO_ENABLE
  #define STARTUP_SONG SONG(S__NOTE(_E4))
  #define GOODBYE_SONG SONG(S__NOTE(_C4))
#endif

// for sanwa keyboard emulation KVM
#undef NKRO_ENABLE

#define USB_POLLING_INTERVAL_MS 5

