SRC += xtonhasvim.c

COMMAND_ENABLE = no
AUDIO_ENABLE = yes
BACKLIGHT_ENABLE = yes
KEY_LOCK_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_MACRO_NO_NESTING = true
MOUSEKEY_ENABLE = yes

USER_NAME := ppy

